# Generated by Django 2.0.2 on 2018-02-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
    ]
