# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talk',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('Speaker', models.CharField(max_length=20)),
                ('Venue', models.CharField(max_length=20)),
                ('Duration', models.IntegerField()),
            ],
        ),
    ]
