# Generated by Django 2.0.2 on 2018-02-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empLeaveData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_balance', models.IntegerField()),
                ('sick_balance', models.IntegerField()),
                ('holiday_balance', models.IntegerField()),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empLeaveData.Employee')),
            ],
        ),
    ]
