# Generated by Django 2.0.2 on 2018-02-07 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverecords',
            name='id',
        ),
        migrations.AlterField(
            model_name='leaverecords',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='empLeaveData.Employee'),
        ),
    ]
