# Generated by Django 2.0.2 on 2018-02-06 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('dept_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_contact', models.CharField(max_length=10)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empLeaveData.Dept')),
            ],
        ),
    ]
